### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by skalee** [riboseinc/enmail#102]
- [ ] Do a version bump to 0.2
- [ ] Push it to RubyGems

Currently, the only known bug is #101. We always specify "pgp-sha1" as "micalg" parameter for "multipart/signed" MIME type, disregarding what digest algorithm we actually use during signature calculation. Both RNP and GPGME adapters are affected, and in the latter case fixing it may be non-trivial.

This bug does not break signature in any way, however it makes one-pass verification impossible. Nevertheless, `mail-gpg` gem does exactly the same…

I am fixing it now, but perhaps it is not critical, and we can make a release.

cc @ronaldtse @ribose-jeffreylau

**Comment by skalee** [comment]
@ronaldtse Could you please add me to https://rubygems.org/gems/enmail, so I can make releases?

**Comment by ronaldtse** [comment]
@skalee done!

**Comment by skalee** [comment]
Thanks! Version 0.2 has been released.
