### ISSUE TITLE
Support Ruby 2.6

### ISSUE THREAD

**Issue by skalee** [riboseinc/enmail#118]
EnMail tests [fail in Travis](https://travis-ci.org/riboseinc/enmail/jobs/477901440) when run against Ruby 2.6 (i.e. `rnp_op_sign_execute failed - (rc: 0x10000000): Unknown error`). On my local computer, on the other hand, they all pass.

**Comment by ronaldtse** [comment]
Thanks @skalee ! I sent you a message — can you let me know?

**Comment by skalee** [comment]
Ruby 2.6 has been added to Travis matrix in #116. Aforementioned failures seem to stopped since merging https://github.com/riboseinc/rspec-pgp_matchers/pull/31. Hopefully they won't appear again like other file descriptor issues.
