### ISSUE TITLE
Ensure dependencies' versions in adapters

### ISSUE THREAD

**Issue by skalee** [riboseinc/enmail#123]
EnMail works with recent versions of GPGME and RNP, which are its optional dependencies. However, dependency version constraints cannot be specified easily, because gem specification does not support the concept of optional dependencies. In effect, no constraints are applied when EnMail is used as a dependency of another gem, which is incorrect.

Rails enforces version constraints by calling `gem` method from source files: https://github.com/rails/rails/blob/f4a30d2a0706f278a20c63a3d99288de79b52e5f/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L12-L13

However, that source file is loaded only if application is configured to work with SQLite3 database. It is not the case in EnMail, in which adapter source files are always loaded. Hence, above pattern cannot be applied in EnMail easily, as optional dependencies would become mandatory ones. Also, I don't like that version constraint is repeated rather than reused (there is an identical constraint next to the `add_development_dependency` in gemspec).

Following approaches should be considered:

1. We can rescue from exception raised by `gem` method in case given dependency is unavailable, and behave accordingly. That eliminates the need for conditional source file load.
2. We can use [Zeitwerk](https://github.com/fxn/zeitwerk#supported-ruby-versions) to conditionally load source files when given adapter is first used. Then we will be able to simply write `gem` in a source file, in a Rails way. Zeitgeist will be intensively used in Rails 6, so I guess we can consider it a stable thing. On the other hand, it bumps minimum Ruby version to MRI 2.4.4.

Regarding constraint duplication, we may leverage RubyGems API, and read this constraint from a development dependency stated in gemspec. The difficult part is to make it nice and readable.

**Comment by ronaldtse** [comment]
It seems that Zeitwerk is reasonable. Any thoughts @ribose-jeffreylau ?

**Comment by skalee** [comment]
I'm pretty convinced that we should go with Zeitwerk-backed solution too. [MRI 2.3 maintenance will end in a less than a month](https://www.ruby-lang.org/en/downloads/branches/), therefore I suppose that nearly every actively maintained web application will switch to at least 2.4 very soon. Surely there are some teams sticking to older Rubies, but probably this is because they have bigger issues to deal with rather than integrating EnMail. :)

**Comment by ribose-jeffreylau** [comment]
Yes, we don't have to worry too much about pre-MRI 2.4.4.
Zeitwerk seems interesting.  Worth a try IMHO.

**Comment by skalee** [comment]
Unfortunately and contrary to what I wrote previously, Zeitwerk won't help much in our case. Integrating it is a purely aesthetic thing, but due to Ruby version requirements, I'll rather skip it for now.

I've already submitted a feature request to address what we need.

**Comment by ronaldtse** [comment]
Thanks @skalee !

**Comment by skalee** [comment]
Regarding Zeitwerk, we may consider integrating it in future. I don't see that much value in it at this point, nevertheless it's quite trivial to do so.

**Comment by skalee** [comment]
Ouch, actually no, it is not fixed yet.
