### ISSUE TITLE
Consider splitting it to EnMail and EnMail-Rails

### ISSUE THREAD

**Issue by skalee** [riboseinc/enmail#21]
Right now EnMail does not depend on `rails`, just on `mail` gem, which makes it more general. We should consider creating a separate gem `enmail-rails` which will bridge features to ActionMailer in a most convenient way.

**Comment by ronaldtse** [comment]
@skalee you’re right. Agree!

**Comment by skalee** [comment]
A new repository https://github.com/riboseinc/enmail-rails has been created. It doesn't contain anything special yet, but all future Rails-related issues or requests should be posted there.

**Comment by ronaldtse** [comment]
Thanks @skalee !
