### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by skalee** [riboseinc/enmail#32]
- [x] Convert to AsciiDoc
- [x] More badges
- [x] ~~Real usage notes, examples~~
- [x] Adapter features comparison table
- [x] ~~Inform about current state of the project~~
- [ ] Reference links to RFCs
- [x] Write few words about project path length limitations (due to UNIX sockets created in project's `tmp/gpgme`)
- [x] Write few words about recreating GPG keys
- [x] Relax code style requirements, or enforce them in style guide (we don't follow all the Sandi Metz's rules, 5 lines per method is pretty harsh).

**Comment by ribose-jeffreylau** [comment]
Hi @skalee , the README does not seem to be updated.  Could you help update it please?  Thanks!

**Comment by skalee** [comment]
Request for more usage examples extracted to #112, and #113.

**Comment by skalee** [comment]
Since version 0.2, this gem is in an usable shape, therefore I suppose there is no need to "inform about current state of the project". I'm scratching that one from TODO list.

**Comment by skalee** [comment]
"Reference links to RFCs" can be find in adapter-specific guides from some time. It was the last item in TODO list, so I'm closing this issue.
