### ISSUE TITLE
Extract RSpec matchers for GPG into a separate gem

### ISSUE THREAD

**Issue by skalee** [riboseinc/enmail#34]
They're generally useful.

**Comment by ribose-jeffreylau** [comment]
Hi @skalee , I think this is potentially very useful.

https://github.com/jkraemer/mail-gpg has implemented methods `encrypted?`, `signed?`, `signature_valid?`, etc on the `Mail` object, which makes it easy for gem users to test e.g. whether the signature is a valid one.  This means I could simply do the following in my RSpec:

```ruby
it 'has a valid signature' do
  expect(mail).to be_signed
  expect(mail).to be_signature_valid
end
```

I tried to do similar things with `enmail` by `require`-ing the specific matcher files via `Gem::Specification` paths, but ended up with what appears to be scoping issues of some variables (e.g. `text` from `GpgMatcherHelper`).  It would appear that by having the RSpec matchers extracted would solve this problem.  The specific matcher I tried to use was `be_a_valid_pgp_signature_of`.

Perhaps implementing something like `Mail#signature_valid?` would also be useful, as a gem user doesn't need to care about extracting the signature string from the `Mail` object while all he cares is whether the `Mail` object contains a valid PGP signature.

**Comment by skalee** [comment]
At the very moment, these matchers rely on some configuration in other support files, notably PGP home directory location. Perhaps this is why they don't work outside EnMail? I don't know, I'll investigate later this week. Or is it urgent to you?

I remember I was considering writing `be_a_valid_pgp_signature` matcher (instead of `be_a_valid_pgp_signature_of`) which wouldn't require passing cleartext. I had some reason to drop this idea, but I don't remember details now. I'll think about it though, now I have way deeper knowledge about OpenPGP, GPG, and GPGME.

**Comment by ribose-jeffreylau** [comment]
hi @skalee , thanks for the response.  We're actually currently relying on `mail-gpg` for the `#signature_valid?` methods to be used in our application RSpec, but it's a dependency that we'd like to remove asap.

**Comment by skalee** [comment]
Major difference between my matchers and matchers from `mail-gpg` is that mine rely on GnuPG executables whereas the latter on GPGME. The purpose is to get rid of GPGME hard dependency in order to test #86 properly. I don't mind using RNP executables instead, but that's future thing.

**Comment by ribose-jeffreylau** [comment]
I see, thanks for the clarification!

**Comment by ronaldtse** [comment]
@skalee in this case can we use GPG command line for the matchers? This will help us remove `mail-gpg`. Thanks!

**Comment by skalee** [comment]
Yes. with #63 in mind.

**Comment by skalee** [comment]
A brand new repository has been created: https://github.com/riboseinc/rspec-pgp_matchers. The gem is not ready for use yet, nevertheless all further requests should be posted there.

**Comment by skalee** [comment]
@ribose-jeffreylau it still needs few more touches like easier configuration, but is mature enough to try in your projects. I hope you'll like it. Feedback is welcome, please report problems and request for features in the issue tracker.

In order to use it, you need to define `TMP_PGP_HOME` constant — it should be a string with a path to PGP home you are going to use.

I wrote some usage notes in README, nevertheless specs are slightly more detailed.

**Comment by ribose-jeffreylau** [comment]
@skalee Thanks! Much appreciated. We'll try it out.
