### ISSUE TITLE
Integration with mail-gpg

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/enmail#4]
@abunashir the `mail_interceptor/pgp.rb` file currently utilizes some code from the `mail-gpg` gem, so we need to `require` the proper files for it to work.

We don't need the mail interceptor for GnuPG to be loaded by default (because we prefer `ruby-rnp`), but if it is loaded, it should directly require and use code from the `ruby-gpgme` library instead of using `mail-gpg`.

**Comment by ronaldtse** [comment]
@skalee would you have time to help with this? Thanks!

**Comment by skalee** [comment]
Sure @ronaldtse!

**Comment by skalee** [comment]
Since rewrite from scratch in #25, this issue is no longer valid.
