### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by skalee** [riboseinc/enmail#81]
Gemspec says this gem is licensed under MIT license (BTW @ronaldtse, it is a correct choice, isn't it?). However, license files are not present in repository, neither README says a word about them.

**Comment by ronaldtse** [comment]
Yes, let’s go with MIT license for now. Thanks!

**Comment by skalee** [comment]
BTW @ronaldtse, should I change following: https://github.com/riboseinc/enmail/blob/4ed0a65a989e5f49f348aaf5b506dbcdc8faee69/enmail.gemspec#L10-L11

to

```
  spec.authors       = ["Ribose Inc."]
  spec.email         = ["open.source@ribose.com"]
```

?

**Comment by ronaldtse** [comment]
Yes please! Thanks!
