### ISSUE TITLE
Adapter-related dependencies are not truly optional

### ISSUE THREAD

**Issue by skalee** [riboseinc/enmail#86]
RNP and GPGME are soft dependencies, and are not guaranteed to be present in user's system. Gem must work without any of them (except for dependant adapters).

**Comment by ronaldtse** [comment]
@skalee RNP 0.9.2. is released and available on yum.

**Comment by skalee** [comment]
Fixes have been merged, but without accompanying test suite improvements. They are still needed though, hence #100 has been created.
